//==========================================================================
//==               Copyright (c) 2026 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 03/31/2026 07:01:31
//== Synopsys Memory Release: V01R10SZ_1JUL2020
//== 12lp PDK N/A
//==
//== IMDK_ROOT: /home/mhnie/gf12_mc/installer/comp_in_gf12lp_r1db
//== IMDK_TECH: 12lp
//==========================================================================


//wrapperBasePrefix = MBH_ZS
//wrapperPrefix     = MBH_ZSNL
//wrapperName       = MBH_ZSNL_IN12LP_R1DB_W01024B015M02S2_LB

`timescale 1ns / 1ps

module MBH_ZSNL_IN12LP_R1DB_W01024B015M02S2_LB
   (
    input  clk,
    input  cen,
    input  rdwen,
    input  [9:0] a,
    input  [14:0] d,
    input  [14:0] bw,
    output [14:0] q
    );

   // VSIA_Soft_IP_Tag % Vendor SYNOPSYS_INC % Product 12LP % Version v00r00 % Metric 100 % IP_Owner VTMDC % Celltype IP % Cell_Id MBH_ZSNL_IN12LP_R1DB_W01024B015M02S2_LB % Signature 100 % Tag_Spec 3.0 % Date_Time YYYYMMDD % Process_Step Source


   IN12LP_R1DB_W01024B015M02S2_LB R1DB
     (
      .CLK         (clk),
      .CEN         (cen),
      .RDWEN       (rdwen),
      .A           (a),
      .D           (d),
      .BW          (bw),
      .T_LOGIC     (1'b0),
      .T_Q_RST     (1'b0),
      .MA_SAWL     (1'b0),
      .MA_STABAS1  (1'b0),
      .MA_STABAS0  (1'b0),
      .MA_WL       (1'b0),
      .MA_WRAS1    (1'b0),
      .MA_WRAS0    (1'b0),
      .MA_VD1      (1'b0),
      .MA_VD0      (1'b0),
      .MA_WRT      (1'b0),
      .Q           (q),
      .OBSV_CTL    ()
     );

endmodule

